/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  theme: {
    extend: {
      colors: {
            "on-background": "#191c1d",
            "on-secondary-container": "#454386",
            "secondary-container": "#b6b4ff",
            "secondary-fixed-dim": "#c3c0ff",
            "on-primary-fixed": "#0f0069",
            "on-tertiary-fixed-variant": "#7b2f00",
            "tertiary-fixed-dim": "#ffb695",
            "tertiary-container": "#a44100",
            "on-error-container": "#93000a",
            "primary": "#3525cd",
            "error": "#ba1a1a",
            "primary-fixed": "#e2dfff",
            "surface-container-low": "#f3f4f5",
            "surface-variant": "#e1e3e4",
            "secondary-fixed": "#e2dfff",
            "tertiary": "#7e3000",
            "on-secondary": "#ffffff",
            "on-secondary-fixed-variant": "#413f82",
            "inverse-on-surface": "#f0f1f2",
            "surface-tint": "#4d44e3",
            "background": "#f8f9fa",
            "error-container": "#ffdad6",
            "inverse-primary": "#c3c0ff",
            "on-surface-variant": "#464555",
            "surface-dim": "#d9dadb",
            "on-tertiary-container": "#ffd2be",
            "on-tertiary": "#ffffff",
            "surface-container": "#edeeef",
            "on-primary-fixed-variant": "#3323cc",
            "on-secondary-fixed": "#140f54",
            "surface-container-lowest": "#ffffff",
            "outline": "#777587",
            "surface-bright": "#f8f9fa",
            "primary-fixed-dim": "#c3c0ff",
            "outline-variant": "#c7c4d8",
            "on-surface": "#191c1d",
            "on-tertiary-fixed": "#351000",
            "surface-container-highest": "#e1e3e4",
            "inverse-surface": "#2e3132",
            "primary-container": "#4f46e5",
            "on-primary": "#ffffff",
            "on-primary-container": "#dad7ff",
            "on-error": "#ffffff",
            "secondary": "#58579b",
            "surface": "#f8f9fa",
            "surface-container-high": "#e7e8e9",
            "tertiary-fixed": "#ffdbcc"
          },
           fontFamily: {
            "headline": ["Manrope"],
            "body": ["Inter"],
            "label": ["Inter"]
          },
          borderRadius: {"DEFAULT": "0.25rem", "lg": "1rem", "xl": "1.5rem", "full": "9999px"},
    },
  },
  plugins: [],
}

